version: '3'
services:
  admin:
    build:
      context: ./admin-service
    ports:
      - 8080:8080
    depends_on:
      - database
  movie:
    build:
      context: ./movie-service
    ports:
      - 8081:8081
    depends_on:
      - database
  rating:
    build:
      context: ./rating-service
    ports:
      - 8082:8082
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - "./database-service/01-sql-create-tables.sql"
      - "./database-service/02-sql-insert-movie.sql"
