version: '3'
services:
  admin:
    container_name: admin-service
    build:
      context: ./admin-service
    image: jonathangehmayr/admin-service:latest
    ports:
      - 8080:8080

  movie:
    container_name: movie-service
    build:
      context: ./movie-service
    image: jonathangehmayr/movie-service:latest
    ports:
      - 8081:8081

  rating:
    container_name: rating-service
    build:
      context: ./rating-service
    image: jonathangehmayr/rating-service:latest
    ports:
      - 8082:8082
