apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: ccproject22
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22
  template:
    metadata:
      labels:
        app: ccproject22
    spec:
      containers:
      - name: admin
        image: fc44311/ccproject22_admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: ccproject22
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22
  template:
    metadata:
      labels:
        app: ccproject22
    spec:
      containers:
      - name: movie
        image: fc44311/ccproject22_movie

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-deployment
  labels:
    app: ccproject22
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22
  template:
    metadata:
      labels:
        app: ccproject22
    spec:
      containers:
      - name: rating
        image: fc44311/ccproject22_rating

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ccproject22
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ccproject22
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: ccproject22
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30003
