apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: ccproject22-admin
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-admin
  template:
    metadata:
      labels:
        app: ccproject22-admin
    spec:
      containers:
      - name: admin-service
        image: fc44311/admin-service:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: ccproject22-movie
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-movie
  template:
    metadata:
      labels:
        app: ccproject22-movie
    spec:
      containers:
      - name: movie-service
        image: fc44311/movie-service:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-deployment
  labels:
    app: ccproject22-rating
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-rating
  template:
    metadata:
      labels:
        app: ccproject22-rating
    spec:
      containers:
      - name: rating-service
        image: fc44311/rating-service:v1
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /fc44311/ccproject22/1.0.0/ui
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5

--- 
apiVersion: v1
kind: Service
metadata:
  name: admin-service-lb
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: ccproject22-admin
  ports:
    - port: 80
      targetPort: 8080

--- 
apiVersion: v1
kind: Service
metadata:
  name: movie-service-lb
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: ccproject22-movie
  ports:
    - port: 80
      targetPort: 8081

--- 
apiVersion: v1
kind: Service
metadata:
  name: rating-service-lb
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: ccproject22-rating
  ports:
    - port: 80
      targetPort: 8082
