apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: ccproject22-admin
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-admin
  template:
    metadata:
      labels:
        app: ccproject22-admin
    spec:
      containers:
      - name: admin-service
        image: jonathangehmayr/admin-service:latest

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-deployment
  labels:
    app: ccproject22-movie
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-movie
  template:
    metadata:
      labels:
        app: ccproject22-movie
    spec:
      containers:
      - name: movie-service
        image: jonathangehmayr/movie-service:latest  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-deployment
  labels:
    app: ccproject22-rating
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccproject22-rating
  template:
    metadata:
      labels:
        app: ccproject22-rating
    spec:
      containers:
      - name: rating-service
        image: jonathangehmayr/rating-service:latest


--- 
apiVersion: v1
kind: Service
metadata:
  name: admin-service-np
spec:
  type: NodePort
  selector:
    app: ccproject22-admin
  ports:
    - port: 8080
      nodePort: 30000

--- 
apiVersion: v1
kind: Service
metadata:
  name: movie-service-np
spec:
  type: NodePort
  selector:
    app: ccproject22-movie
  ports:
    - port: 8080
      nodePort: 30001

--- 
apiVersion: v1
kind: Service
metadata:
  name: rating-service-np
spec:
  type: NodePort
  selector:
    app: ccproject22-rating
  ports:
    - port: 8080
      nodePort: 30002
