# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Movie(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, movie_id: str=None, movie_title: str=None, movie_release_year: str=None, movie_url: str=None, movie_title_language: str=None, movie_popularity: str=None, movie_image_url: str=None, director_id: str=None, director_name: str=None, director_url: str=None, average_rating: int=None):  # noqa: E501
        """Movie - a model defined in Swagger

        :param movie_id: The movie_id of this Movie.  # noqa: E501
        :type movie_id: str
        :param movie_title: The movie_title of this Movie.  # noqa: E501
        :type movie_title: str
        :param movie_release_year: The movie_release_year of this Movie.  # noqa: E501
        :type movie_release_year: int
        :param movie_url: The movie_url of this Movie.  # noqa: E501
        :type movie_url: str
        :param movie_title_language: The movie_title_language of this Movie.  # noqa: E501
        :type movie_title_language: str
        :param movie_popularity: The movie_popularity of this Movie.  # noqa: E501
        :type movie_popularity: int
        :param movie_image_url: The movie_image_url of this Movie.  # noqa: E501
        :type movie_image_url: str
        :param director_id: The director_id of this Movie.  # noqa: E501
        :type director_id: str
        :param director_name: The director_name of this Movie.  # noqa: E501
        :type director_name: str
        :param director_url: The director_url of this Movie.  # noqa: E501
        :type director_url: str
        :param average_rating: The average_rating of this Movie.  # noqa: E501
        :type average_rating: int
        """
        self.swagger_types = {
            'movie_id': str,
            'movie_title': str,
            'movie_release_year': int,
            'movie_url': str,
            'movie_title_language': str,
            'movie_popularity': int,
            'movie_image_url': str,
            'director_id': str,
            'director_name': str,
            'director_url': str,
            'average_rating': int
        }

        self.attribute_map = {
            'movie_id': 'movie_id',
            'movie_title': 'movie_title',
            'movie_release_year': 'movie_release_year',
            'movie_url': 'movie_url',
            'movie_title_language': 'movie_title_language',
            'movie_popularity': 'movie_popularity',
            'movie_image_url': 'movie_image_url',
            'director_id': 'director_id',
            'director_name': 'director_name',
            'director_url': 'director_url',
            'average_rating': 'average_rating'
        }
        self._movie_id = movie_id
        self._movie_title = movie_title
        self._movie_release_year = movie_release_year
        self._movie_url = movie_url
        self._movie_title_language = movie_title_language
        self._movie_popularity = movie_popularity
        self._movie_image_url = movie_image_url
        self._director_id = director_id
        self._director_name = director_name
        self._director_url = director_url
        self._average_rating = average_rating

    @classmethod
    def from_dict(cls, dikt) -> 'Movie':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The movie of this Movie.  # noqa: E501
        :rtype: Movie
        """
        return util.deserialize_model(dikt, cls)

    @property
    def movie_id(self) -> str:
        """Gets the movie_id of this Movie.


        :return: The movie_id of this Movie.
        :rtype: str
        """
        return self._movie_id

    @movie_id.setter
    def movie_id(self, movie_id: str):
        """Sets the movie_id of this Movie.


        :param movie_id: The movie_id of this Movie.
        :type movie_id: str
        """

        self._movie_id = movie_id

    @property
    def movie_title(self) -> str:
        """Gets the movie_title of this Movie.


        :return: The movie_title of this Movie.
        :rtype: str
        """
        return self._movie_title

    @movie_title.setter
    def movie_title(self, movie_title: str):
        """Sets the movie_title of this Movie.


        :param movie_title: The movie_title of this Movie.
        :type movie_title: str
        """

        self._movie_title = movie_title

    @property
    def movie_release_year(self) -> int:
        """Gets the movie_release_year of this Movie.


        :return: The movie_release_year of this Movie.
        :rtype: int
        """
        return self._movie_release_year

    @movie_release_year.setter
    def movie_release_year(self, movie_release_year: int):
        """Sets the movie_release_year of this Movie.


        :param movie_release_year: The movie_release_year of this Movie.
        :type movie_release_year: int
        """

        self._movie_release_year = movie_release_year

    @property
    def movie_url(self) -> str:
        """Gets the movie_url of this Movie.


        :return: The movie_url of this Movie.
        :rtype: str
        """
        return self._movie_url

    @movie_url.setter
    def movie_url(self, movie_url: str):
        """Sets the movie_url of this Movie.


        :param movie_url: The movie_url of this Movie.
        :type movie_url: str
        """

        self._movie_url = movie_url

    @property
    def movie_title_language(self) -> str:
        """Gets the movie_title_language of this Movie.


        :return: The movie_title_language of this Movie.
        :rtype: str
        """
        return self._movie_title_language

    @movie_title_language.setter
    def movie_title_language(self, movie_title_language: str):
        """Sets the movie_title_language of this Movie.


        :param movie_title_language: The movie_title_language of this Movie.
        :type movie_title_language: str
        """

        self._movie_title_language = movie_title_language

    @property
    def movie_popularity(self) -> int:
        """Gets the movie_popularity of this Movie.


        :return: The movie_popularity of this Movie.
        :rtype: int
        """
        return self._movie_popularity

    @movie_popularity.setter
    def movie_popularity(self, movie_popularity: int):
        """Sets the movie_popularity of this Movie.


        :param movie_popularity: The movie_popularity of this Movie.
        :type movie_popularity: int
        """

        self._movie_popularity = movie_popularity

    @property
    def movie_image_url(self) -> str:
        """Gets the movie_image_url of this Movie.


        :return: The movie_image_url of this Movie.
        :rtype: str
        """
        return self._movie_image_url

    @movie_image_url.setter
    def movie_image_url(self, movie_image_url: str):
        """Sets the movie_image_url of this Movie.


        :param movie_image_url: The movie_image_url of this Movie.
        :type movie_image_url: str
        """

        self._movie_image_url = movie_image_url

    @property
    def director_id(self) -> str:
        """Gets the director_id of this Movie.


        :return: The director_id of this Movie.
        :rtype: str
        """
        return self._director_id

    @director_id.setter
    def director_id(self, director_id: str):
        """Sets the director_id of this Movie.


        :param director_id: The director_id of this Movie.
        :type director_id: str
        """

        self._director_id = director_id

    @property
    def director_name(self) -> str:
        """Gets the director_name of this Movie.


        :return: The director_name of this Movie.
        :rtype: str
        """
        return self._director_name

    @director_name.setter
    def director_name(self, director_name: str):
        """Sets the director_name of this Movie.


        :param director_name: The director_name of this Movie.
        :type director_name: str
        """

        self._director_name = director_name

    @property
    def director_url(self) -> str:
        """Gets the director_url of this Movie.


        :return: The director_url of this Movie.
        :rtype: str
        """
        return self._director_url

    @director_url.setter
    def director_url(self, director_url: str):
        """Sets the director_url of this Movie.


        :param director_url: The director_url of this Movie.
        :type director_url: str
        """

        self._director_url = director_url

    @property
    def average_rating(self) -> int:
        """Gets the average_rating of this Movie.


        :return: The average_rating of this Movie.
        :rtype: int
        """
        return self._average_rating

    @average_rating.setter
    def average_rating(self, average_rating: int):
        """Sets the average_rating of this Movie.


        :param average_rating: The average_rating of this Movie.
        :type average_rating: int
        """

        self._average_rating = average_rating
