openapi: 3.0.0
info:
  title: Movies API
  description: Cloud Computing Project - Movies API
  contact:
    email: fc57267@alunos.fc.ul.pt
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/fc44311/ccproject22/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://app.swaggerhub.com/apis/fc44311/ccproject22/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admin
  description: Perform administration activities (movies and ratings management)
paths:
  /admin/add_movie:
    post:
      tags:
      - admin
      summary: Add a new movie information
      operationId: admin_add_movie
      parameters:
      - name: movie_title
        in: query
        description: Title of the movie
        required: true
        style: form
        explode: false
        schema:
          type: string
      - name: movie_title_language
        in: query
        description: Language of title of the movie
        required: true
        style: form
        explode: false
        schema:
          type: string
      - name: movie_image_url
        in: query
        description: Image url of the movie
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: director_id
        in: query
        description: Title of the movie
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: director_name
        in: query
        description: Title of the movie
        required: false
        style: form
        explode: false
        schema:
          type: string
      - name: director_url
        in: query
        description: Director url
        required: false
        style: form
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Successful operation. Movie added.
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
            application/xml:
              schema:
                type: boolean
        "400":
          description: Bad request. Invalid arguments.
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
            application/xml:
              schema:
                type: boolean
      x-openapi-router-controller: swagger_server.controllers.admin_controller
  /admin/delete_movie/{movie_id}:
    delete:
      tags:
      - admin
      summary: Deleting an existing movie data
      operationId: admin_delete_movie
      parameters:
      - name: movie_id
        in: path
        description: ID related to the movie on Mubi
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "202":
          description: Accepted. Movie deleted.
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
            application/xml:
              schema:
                type: boolean
        "204":
          description: No content. Invalid movie id.
          content:
            application/json:
              schema:
                type: boolean
                x-content-type: application/json
            application/xml:
              schema:
                type: boolean
      x-openapi-router-controller: swagger_server.controllers.admin_controller
components:
  schemas:
    movie:
      type: object
      properties:
        movie_id:
          type: string
        movie_title:
          type: string
        movie_release_year:
          type: integer
        movie_url:
          type: string
        movie_title_language:
          type: string
        movie_popularity:
          type: integer
        movie_image_url:
          type: string
        director_id:
          type: string
        director_name:
          type: string
        director_url:
          type: string
        average_rating:
          type: number
      example:
        movie_id: movie_id
        movie_title: movie_title
        movie_release_year: 2022
        movie_url: movie_url
        movie_title_language: en
        movie_popularity: 0
        movie_image_url: movie_image_url
        director_id: director_id
        director_name: director_name
        director_url: director_url
        average_rating: 0

